apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nginx      # Targets pods with this label.
  ports:
    - protocol: TCP
      port: 80      # External port for accessing the service.
      targetPort: 80  # Internal container port.
