apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-rollout
  namespace: default
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 20      # Update 20% of pods initially.
        - pause: {duration: 5s}  # Pause to monitor the new version.
        - setWeight: 50      # Update 50% of pods next.
        - pause: {duration: 10s}  # Pause again for observation.
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx       # Must match selector in Service.
    spec:
      containers:
        - name: nginx
          image: nginx:latest  # Change to e.g., nginx:1.19 to simulate version update.
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
