apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nginx      # Targets pods with the app: nginx label.
  ports:
    - protocol: TCP
      port: 80      # External port.
      targetPort: 80  # Container port.
