apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-rollout
  namespace: default
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 20      # Update 20% of pods initially.
        - pause: {duration: 10s}  # Pause to monitor the new version.
        - setWeight: 50      # Update 50% of pods next.
        - pause: {duration: 20s}  # Pause again for observation.
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx       # This label is used to match pods with the Service.
    spec:
      containers:
        - name: nginx
          image: nginx:latest  # Starting with the latest version.
          ports:
            - containerPort: 80
          readinessProbe:             # Added readiness probe
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
